import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFExporter } from 'three/addons/exporters/GLTFExporter.js';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { AfterimagePass } from 'three/addons/postprocessing/AfterimagePass.js';
import { RoundedBoxGeometry } from 'three/addons/geometries/RoundedBoxGeometry.js';

const LIME=0xd8ff1e, ROCK=0x262826, WHITE=0xf7f6f0, BLACK=0x070807;
const stage=document.getElementById('stage');
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.06;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;stage.appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color(0x020302);scene.fog=new THREE.FogExp2(0x020302,.022);
const camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.1,150);camera.position.set(7.2,4.8,11.6);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(0,1.25,0);controls.minDistance=6;controls.maxDistance=22;
scene.add(new THREE.HemisphereLight(0xffffff,0x090b08,2.15));
const key=new THREE.DirectionalLight(0xffffff,5.6);key.position.set(6,10,8);key.castShadow=true;scene.add(key);
const rim=new THREE.PointLight(LIME,95,20,2);rim.position.set(-5,5,-4);scene.add(rim);
const fill=new THREE.PointLight(0x93a8ff,12,16,2);fill.position.set(5,1,-6);scene.add(fill);
const warm=new THREE.PointLight(0xfff0cf,18,14,2);warm.position.set(-3,1,7);scene.add(warm);

const composer=new EffectComposer(renderer);const renderPass=new RenderPass(scene,camera);composer.addPass(renderPass);const bloomPass=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),1.2,.58,.66);composer.addPass(bloomPass);const afterPass=new AfterimagePass(.91);composer.addPass(afterPass);

const floorMat=new THREE.MeshStandardMaterial({color:0x060706,roughness:.94,metalness:.03});const floor=new THREE.Mesh(new THREE.CircleGeometry(20,96),floorMat);floor.rotation.x=-Math.PI/2;floor.position.y=-2.78;floor.receiveShadow=true;scene.add(floor);
const shadow=new THREE.Mesh(new THREE.CircleGeometry(3.1,64),new THREE.MeshBasicMaterial({color:0x000000,transparent:true,opacity:.36,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=-2.755;shadow.scale.set(1.4,.6,1);scene.add(shadow);

const character=new THREE.Group();scene.add(character);character.position.set(0,.35,0);const clean=new THREE.Group();character.add(clean);
const rockMat=new THREE.MeshStandardMaterial({color:ROCK,roughness:.84,metalness:.04});const darkMat=new THREE.MeshStandardMaterial({color:BLACK,roughness:.55,metalness:.06});const rubberMat=new THREE.MeshStandardMaterial({color:0x111311,roughness:.75,metalness:.03});const whiteMat=new THREE.MeshPhysicalMaterial({color:WHITE,roughness:.3,clearcoat:.15,clearcoatRoughness:.25});const limeMat=new THREE.MeshStandardMaterial({color:LIME,roughness:.22,metalness:.04,emissive:LIME,emissiveIntensity:.55});

let seed=9917;const rnd=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646};
const craters=[];for(let i=0;i<42;i++){let u=rnd()*2-1,a=rnd()*Math.PI*2,s=Math.sqrt(1-u*u),c=new THREE.Vector3(s*Math.cos(a),u,s*Math.sin(a));if(c.z>.58&&Math.abs(c.x)<.76&&c.y<.72){i--;continue}craters.push({c,r:.055+rnd()*.12,d:.035+rnd()*.075,rim:.012+rnd()*.018});}
craters.push({c:new THREE.Vector3(-.30,.91,.23).normalize(),r:.18,d:.12,rim:.026},{c:new THREE.Vector3(.20,.92,.18).normalize(),r:.13,d:.10,rim:.022},{c:new THREE.Vector3(.74,.60,.28).normalize(),r:.14,d:.10,rim:.021},{c:new THREE.Vector3(-.72,.62,.30).normalize(),r:.11,d:.075,rim:.018});
function sculptBody(){const g=new THREE.SphereGeometry(2.48,144,112);const p=g.attributes.position;const v=new THREE.Vector3();for(let i=0;i<p.count;i++){v.fromBufferAttribute(p,i);const n=v.clone().normalize();let R=2.48*(1+.012*Math.sin(n.x*13+n.y*8)+.008*Math.sin(n.z*17-n.x*5));for(const q of craters){const ang=Math.acos(THREE.MathUtils.clamp(n.dot(q.c),-1,1));const t=ang/q.r;if(t<1){const core=Math.pow(Math.cos(t*Math.PI/2),2);R-=q.d*2.48*core;}if(t>.72&&t<1.22){const rimv=Math.exp(-Math.pow((t-.98)/.115,2));R+=q.rim*2.48*rimv;}}const crest=Math.max(0,n.y*.72+n.x*.28+n.z*.12-.53);R+=crest*crest*.22;v.copy(n).multiplyScalar(R);v.x*=1.01;v.y*=1.025;v.z*=.985;p.setXYZ(i,v.x,v.y,v.z);}g.computeVertexNormals();return g}
const body=new THREE.Mesh(sculptBody(),rockMat);body.castShadow=true;body.receiveShadow=true;clean.add(body);

function eyeTexture(letter){const c=document.createElement('canvas');c.width=c.height=1024;const x=c.getContext('2d');const grd=x.createRadialGradient(380,300,30,512,520,445);grd.addColorStop(0,'#efffd3');grd.addColorStop(.32,'#d8ff1e');grd.addColorStop(.76,'#a3d400');grd.addColorStop(1,'#6b9200');x.fillStyle=grd;x.beginPath();x.arc(512,512,430,0,Math.PI*2);x.fill();x.fillStyle='#050605';x.beginPath();x.arc(512,520,265,0,Math.PI*2);x.fill();x.strokeStyle='rgba(255,255,255,.8)';x.lineWidth=22;x.beginPath();x.arc(512,512,416,0,Math.PI*2);x.stroke();x.fillStyle='#d8ff1e';x.font='900 italic 330px Arial Black,Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(letter,520,535);x.fillStyle='white';x.beginPath();x.ellipse(382,325,82,52,-.45,0,Math.PI*2);x.fill();x.save();x.translate(680,315);x.rotate(Math.PI/4);x.fillRect(-13,-58,26,116);x.fillRect(-58,-13,116,26);x.restore();const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return t}
function makeEye(x,letter,tilt=0){const g=new THREE.Group();const socket=new THREE.Mesh(new THREE.SphereGeometry(.86,64,48),darkMat);socket.scale.set(1.05,.95,.34);g.add(socket);const white=new THREE.Mesh(new THREE.SphereGeometry(.77,64,48),whiteMat);white.scale.set(1,.94,.30);white.position.z=.07;g.add(white);const irisMat=new THREE.MeshStandardMaterial({map:eyeTexture(letter),roughness:.16,metalness:.02,emissive:LIME,emissiveIntensity:.48});const iris=new THREE.Mesh(new THREE.CircleGeometry(.585,96),irisMat);iris.position.z=.315;g.add(iris);const lens=new THREE.Mesh(new THREE.CircleGeometry(.60,96),new THREE.MeshPhysicalMaterial({color:0xffffff,transparent:true,opacity:.12,roughness:.02,transmission:.18,clearcoat:1,depthWrite:false}));lens.position.z=.326;g.add(lens);g.position.set(x,.48,2.27);g.rotation.z=tilt;g.userData.irisMat=irisMat;return g}
const eyeL=makeEye(-.82,'O',-.035),eyeR=makeEye(.82,'G',.035);clean.add(eyeL,eyeR);
function brow(x,rot){const m=new THREE.Mesh(new RoundedBoxGeometry(1.22,.31,.28,5,.14),rockMat);m.position.set(x,1.36,2.24);m.rotation.z=rot;m.rotation.x=-.05;m.castShadow=true;return m}const browL=brow(-.83,-.14),browR=brow(.83,.14);clean.add(browL,browR);

function mouthShape(){const s=new THREE.Shape();s.moveTo(-1.46,.30);s.quadraticCurveTo(0,-.02,1.46,.30);s.quadraticCurveTo(1.23,-.82,0,-.96);s.quadraticCurveTo(-1.23,-.82,-1.46,.30);return s}
const mouthCavity=new THREE.Mesh(new THREE.ExtrudeGeometry(mouthShape(),{depth:.14,bevelEnabled:true,bevelSegments:5,steps:1,bevelSize:.06,bevelThickness:.05}),darkMat);mouthCavity.position.set(0,-.69,2.18);clean.add(mouthCavity);
const innerGlow=new THREE.Mesh(new THREE.ShapeGeometry(mouthShape()),new THREE.MeshBasicMaterial({color:LIME,transparent:true,opacity:.32,blending:THREE.AdditiveBlending,depthWrite:false}));innerGlow.scale.set(.91,.60,1);innerGlow.position.set(0,-1.08,2.37);clean.add(innerGlow);
function wordTex(){const c=document.createElement('canvas');c.width=1400;c.height=380;const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.save();x.translate(c.width/2,c.height/2);x.rotate(-.025);x.font='900 italic 225px Arial Black,Arial';x.textAlign='center';x.textBaseline='middle';x.lineWidth=14;x.strokeStyle='#111';x.strokeText('FASTR',0,0);const grad=x.createLinearGradient(0,-100,0,110);grad.addColorStop(0,'#fff');grad.addColorStop(.52,'#f1efe8');grad.addColorStop(1,'#bfc2bc');x.fillStyle=grad;x.fillText('FASTR',0,0);x.restore();const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return t}
const wordMat=new THREE.MeshPhysicalMaterial({map:wordTex(),transparent:true,roughness:.18,metalness:.62,clearcoat:.3});const word=new THREE.Mesh(new THREE.PlaneGeometry(2.65,.72),wordMat);word.position.set(0,-.97,2.43);word.rotation.z=-.012;clean.add(word);

function limbSide(sign){const g=new THREE.Group();const arm=new THREE.Mesh(new THREE.CapsuleGeometry(.30,.62,12,28),rubberMat);arm.position.set(sign*2.27,-.18,.03);arm.rotation.z=sign*.16;g.add(arm);const hand=new THREE.Mesh(new THREE.SphereGeometry(.47,44,32),rubberMat);hand.scale.set(.95,1.05,.88);hand.position.set(sign*2.53,-.79,.10);g.add(hand);return {g,arm,hand}}
const L=limbSide(-1),R=limbSide(1);clean.add(L.g,R.g);
function shoe(side){const g=new THREE.Group();const upper=new THREE.Mesh(new THREE.SphereGeometry(.72,56,40),rubberMat);upper.scale.set(1.15,.72,1.50);upper.position.y=.18;g.add(upper);const sole=new THREE.Mesh(new RoundedBoxGeometry(1.56,.29,1.96,8,.14),whiteMat);sole.position.y=-.25;g.add(sole);const outsole=new THREE.Mesh(new RoundedBoxGeometry(1.47,.16,1.84,8,.10),darkMat);outsole.position.y=-.43;g.add(outsole);const stripe=new THREE.Mesh(new RoundedBoxGeometry(.18,.20,1.22,4,.07),limeMat);stripe.position.set(side*.54,.10,.06);stripe.rotation.y=side*.02;g.add(stripe);return {g,upper,sole,outsole,stripe}}
const shoeL=shoe(-1),shoeR=shoe(1);shoeL.g.position.set(-.76,-2.30,.06);shoeR.g.position.set(.76,-2.30,.06);clean.add(shoeL.g,shoeR.g);
const legL=new THREE.Mesh(new THREE.CapsuleGeometry(.26,.40,10,20),rubberMat),legR=legL.clone();legL.position.set(-.76,-1.95,.05);legR.position.set(.76,-1.95,.05);clean.add(legL,legR);
function cometTexture(){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d');x.clearRect(0,0,512,512);x.fillStyle='#d8ff1e';x.beginPath();x.arc(315,256,72,0,Math.PI*2);x.fill();x.beginPath();x.moveTo(285,215);x.lineTo(78,145);x.lineTo(260,244);x.closePath();x.fill();x.beginPath();x.moveTo(285,290);x.lineTo(100,350);x.lineTo(260,267);x.closePath();x.fill();const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function soleDecal(shoe){const p=new THREE.Mesh(new THREE.PlaneGeometry(.78,.78),new THREE.MeshBasicMaterial({map:cometTexture(),transparent:true,side:THREE.DoubleSide}));p.rotation.x=Math.PI/2;p.position.set(0,-.525,.15);shoe.g.add(p)}soleDecal(shoeL);soleDecal(shoeR);

const vfx=new THREE.Group();scene.add(vfx);vfx.position.copy(character.position);
const tailUniforms=[];const tailCurves=[];
const strandDefs=[[[1.55,1.55,-1.0],[3.15,2.35,-2.0],[5.25,3.65,-4.1],[7.8,4.2,-7.6]],[[1.30,1.20,-1.2],[2.75,1.95,-2.5],[4.7,2.65,-4.8],[7.0,2.9,-8.2]],[[1.15,.85,-1.25],[2.55,.9,-2.8],[4.6,1.2,-5.0],[6.5,.8,-8.0]],[[.75,1.78,-1.0],[2.0,3.0,-2.5],[4.2,4.6,-4.7],[7.2,5.25,-7.4]]];
const vshader=`varying vec2 vUv; uniform float uTime; uniform float uWave; void main(){vUv=uv;vec3 p=position;float taper=(1.0-vUv.x);p += normal*sin(uTime*2.0+vUv.x*18.0+uWave)*0.028*taper;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.0);}`;
const fshader=`varying vec2 vUv;uniform float uTime;uniform float uStrength;uniform vec3 uColor;void main(){float along=1.0-vUv.x;float edge=pow(abs(sin(vUv.y*3.14159)),1.8);float pulse=.72+.28*sin(uTime*3.2-vUv.x*22.0);float core=smoothstep(.10,.65,edge);float a=pow(along,.42)*core*pulse*uStrength;vec3 col=mix(uColor,vec3(1.0),pow(core,4.0)*.72);gl_FragColor=vec4(col,a);}`;
strandDefs.forEach((pts,i)=>{const curve=new THREE.CatmullRomCurve3(pts.map(p=>new THREE.Vector3(...p)));tailCurves.push(curve);const geo=new THREE.TubeGeometry(curve,140,.11+i*.025,10,false);const uniforms={uTime:{value:0},uStrength:{value:.62-i*.06},uWave:{value:i*1.7},uColor:{value:new THREE.Color(i===0?0xd8ff1e:0xb8ff12)}};tailUniforms.push(uniforms);const mat=new THREE.ShaderMaterial({uniforms,vertexShader:vshader,fragmentShader:fshader,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,side:THREE.DoubleSide});const m=new THREE.Mesh(geo,mat);vfx.add(m)});
const particleN=260;const pgeo=new THREE.BufferGeometry();const pos=new Float32Array(particleN*3),phase=new Float32Array(particleN);for(let i=0;i<particleN;i++){phase[i]=Math.random();const q=tailCurves[i%tailCurves.length].getPoint(phase[i]);pos.set([q.x+(Math.random()-.5)*.7,q.y+(Math.random()-.5)*.7,q.z+(Math.random()-.5)*.7],i*3)}pgeo.setAttribute('position',new THREE.BufferAttribute(pos,3));const pmat=new THREE.PointsMaterial({color:LIME,size:.055,transparent:true,opacity:.82,blending:THREE.AdditiveBlending,depthWrite:false});const particles=new THREE.Points(pgeo,pmat);vfx.add(particles);
const debris=new THREE.Group();vfx.add(debris);for(let i=0;i<14;i++){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(.06+Math.random()*.16,1),rockMat.clone());const q=tailCurves[i%4].getPoint(.12+Math.random()*.84);m.position.copy(q).add(new THREE.Vector3((Math.random()-.5)*1.1,(Math.random()-.5)*1.1,(Math.random()-.5)*1.1));debris.add(m)}

let mode='hero',anim='run',hero=true,world=false,jumpPhase=0;const keys={};addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space')jumpPhase=.001});addEventListener('keyup',e=>keys[e.code]=false);
function setMode(m){mode=m;hero=m==='hero';world=m==='world';document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));document.getElementById('modeLabel').textContent=hero?'Hero motion':world?'Run world':'Studio inspection';controls.enabled=!world;afterPass.enabled=hero||world;if(m==='inspect'){anim='idle';document.querySelectorAll('.anim').forEach(b=>b.classList.toggle('active',b.dataset.anim==='idle'));camera.position.set(7.2,4.6,11.8);controls.target.set(0,.7,0)}if(m==='hero'){anim='run';document.querySelectorAll('.anim').forEach(b=>b.classList.toggle('active',b.dataset.anim==='run'));camera.position.set(6.8,4.2,11.2);controls.target.set(0,.8,0)}}
function setView(v){const views={front:[0,1.3,13],three:[7.2,4.4,11.4],side:[13,1.2,.1],back:[0,1.2,-13],top:[.1,13,.1]};camera.position.set(...views[v]);controls.target.set(0,.6,0);controls.update()}
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('.anim').forEach(b=>b.onclick=()=>{anim=b.dataset.anim;document.querySelectorAll('.anim').forEach(x=>x.classList.toggle('active',x===b));if(anim==='jump')jumpPhase=.001});
const tailToggle=document.getElementById('tailToggle'),particleToggle=document.getElementById('particleToggle'),blurToggle=document.getElementById('blurToggle');document.getElementById('bloom').oninput=e=>bloomPass.strength=+e.target.value;document.getElementById('tailStrength').oninput=e=>tailUniforms.forEach((u,i)=>u.uStrength.value=(.52-i*.05)*+e.target.value);document.getElementById('eyeGlow').oninput=e=>{eyeL.userData.irisMat.emissiveIntensity=+e.target.value;eyeR.userData.irisMat.emissiveIntensity=+e.target.value};document.getElementById('roughness').oninput=e=>rockMat.roughness=+e.target.value;document.getElementById('wire').onchange=e=>rockMat.wireframe=e.target.checked;

function pose(t){const speed=anim==='sprint'?11:anim==='run'?7.4:anim==='jump'?5:2.2;const k=t*speed;const moving=anim==='run'||anim==='sprint';const amp=anim==='sprint'?1.0:.72;character.rotation.z=Math.sin(k*.5)*.018;character.rotation.x=-.02;character.position.y=.35+(moving?Math.abs(Math.sin(k))*.10:Math.sin(t*2.2)*.025);L.g.rotation.x=moving?Math.sin(k)*.88*amp:0;R.g.rotation.x=moving?Math.sin(k+Math.PI)*.88*amp:0;shoeL.g.rotation.x=moving?Math.sin(k+Math.PI)*.50*amp:0;shoeR.g.rotation.x=moving?Math.sin(k)*.50*amp:0;shoeL.g.position.z=moving?Math.sin(k+Math.PI)*.64*amp:.06;shoeR.g.position.z=moving?Math.sin(k)*.64*amp:.06;shoeL.g.position.y=-2.30+(moving?Math.abs(Math.sin(k+Math.PI))*.26:0);shoeR.g.position.y=-2.30+(moving?Math.abs(Math.sin(k))*.26:0);if(jumpPhase>0){jumpPhase+=.035;character.position.y+=Math.sin(Math.min(1,jumpPhase)*Math.PI)*2.0;if(jumpPhase>=1)jumpPhase=0}}
function updateParticles(t){const a=pgeo.attributes.position.array;for(let i=0;i<particleN;i++){let u=(phase[i]+t*.11*(i%3+1))%1;const c=tailCurves[i%4],q=c.getPoint(u);a[i*3]=q.x+Math.sin(i*12.1+t*2)*.26;a[i*3+1]=q.y+Math.cos(i*8.3+t*1.6)*.25;a[i*3+2]=q.z+Math.sin(i*3.7+t)*.28}pgeo.attributes.position.needsUpdate=true}
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const t=clock.getElapsedTime();pose(t);vfx.position.copy(character.position);tailUniforms.forEach(u=>u.uTime.value=t);vfx.visible=tailToggle.checked;particles.visible=particleToggle.checked;debris.visible=particleToggle.checked;updateParticles(t);debris.children.forEach((m,i)=>{m.rotation.x+=.007*(i%3+1);m.rotation.y+=.009*(i%4+1)});afterPass.enabled=blurToggle.checked&&(hero||world);if(document.getElementById('rotateToggle').checked&&!world)character.rotation.y+=.004;if(world){const sprint=keys.ShiftLeft||keys.ShiftRight;anim=sprint?'sprint':'run';const zSpeed=sprint?.36:.22;for(const s of scene.children){if(s.userData.worldTile){s.position.z+=zSpeed;if(s.position.z>12)s.position.z-=80}}if(keys.Space&&jumpPhase===0)jumpPhase=.001;}controls.update();composer.render();}
for(let i=0;i<30;i++){const tile=new THREE.Mesh(new THREE.PlaneGeometry(9,1.6),new THREE.MeshBasicMaterial({color:i%2?0x0d130b:0x111810,transparent:true,opacity:.58,side:THREE.DoubleSide}));tile.rotation.x=-Math.PI/2;tile.position.set(0,-2.74,-i*2.7);tile.userData.worldTile=true;scene.add(tile)}
async function exportClean(){const old=vfx.visible;vfx.visible=false;const clone=clean.clone(true);const ex=new GLTFExporter();const data=await ex.parseAsync(clone,{binary:true,onlyVisible:true});const blob=new Blob([data],{type:'model/gltf-binary'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='OG_FASTR_clean_character_v6.glb';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);vfx.visible=old}document.getElementById('exportGLB').onclick=exportClean;document.getElementById('shot').onclick=()=>{renderer.render(scene,camera);const a=document.createElement('a');a.href=renderer.domElement.toDataURL('image/png');a.download='OG_FASTR_v6.png';a.click()};
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight)});
setMode('hero');setTimeout(()=>document.getElementById('loading').classList.add('hide'),700);animate();