const LIME=0xd8ff1e, ROCK=0x141715, BLACK=0x030403, OFFWHITE=0xf3f2e9;
const stage=document.getElementById('stage'),loading=document.getElementById('loading'),modeLabel=document.getElementById('modeLabel');
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.92;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;stage.appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color(0x020302);scene.fog=new THREE.FogExp2(0x020302,.013);const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(renderer),.022).texture;
const camera=new THREE.PerspectiveCamera(35,innerWidth/innerHeight,.05,180);camera.position.set(7.35,4.35,13.9);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.055;controls.target.set(0,.08,0);controls.minDistance=6;controls.maxDistance=24;
scene.add(new THREE.HemisphereLight(0xffffff,0x050805,1.28));const key=new THREE.DirectionalLight(0xfffdf5,2.75);key.position.set(5.8,9.8,10.8);key.castShadow=true;key.shadow.mapSize.set(2048,2048);scene.add(key);const fill=new THREE.DirectionalLight(0xcbd4ff,.60);fill.position.set(-5,2,8);scene.add(fill);const rim=new THREE.PointLight(LIME,7.0,17,2);rim.position.set(-5,4,-5);scene.add(rim);const backWhite=new THREE.PointLight(0xffffff,5.2,18,2);backWhite.position.set(4,7,-6);scene.add(backWhite);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(160,160),new THREE.MeshStandardMaterial({color:0x030403,roughness:.97,metalness:.01}));floor.rotation.x=-Math.PI/2;floor.position.y=-3.22;floor.receiveShadow=true;scene.add(floor);const grid=new THREE.GridHelper(160,160,0x11160e,0x070a07);grid.position.y=-3.2;grid.material.opacity=.03;grid.material.transparent=true;scene.add(grid);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloomPass=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.40,.58,1.78);composer.addPass(bloomPass);const afterPass=new AfterimagePass(.72);afterPass.enabled=false;composer.addPass(afterPass);
const character=new THREE.Group();character.name='OG_FASTR_CLEAN_MASTER';scene.add(character);character.position.y=.18;const core=new THREE.Group();core.name='PRINTABLE_CORE';character.add(core);const vfx=new THREE.Group();vfx.name='SEPARATE_COMET_VFX';character.add(vfx);
function makeRockBump(){const c=document.createElement('canvas');c.width=c.height=768;const x=c.getContext('2d'),id=x.createImageData(768,768);let r=82736123;const rand=()=>{r=(r*1664525+1013904223)>>>0;return r/4294967296};for(let yy=0;yy<768;yy++)for(let xx=0;xx<768;xx++){const i=(yy*768+xx)*4,coarse=7*Math.sin(xx*.070)+5*Math.cos(yy*.09)+3*Math.sin((xx+yy)*.045),grain=(rand()-.5)*24,v=Math.max(38,Math.min(214,118+coarse+grain));id.data[i]=id.data[i+1]=id.data[i+2]=v;id.data[i+3]=255}x.putImageData(id,0,0);for(let i=0;i<520;i++){const px=rand()*768,py=rand()*768,rr=.4+rand()*2.2;x.fillStyle=`rgba(12,12,12,${.03+rand()*.07})`;x.beginPath();x.arc(px,py,rr,0,Math.PI*2);x.fill()}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(4.0,2.8);t.colorSpace=THREE.NoColorSpace;return t}
const rockBump=makeRockBump();const bodyMat=new THREE.MeshStandardMaterial({color:0xffffff,vertexColors:true,roughness:.80,metalness:.02,bumpMap:rockBump,bumpScale:.060,envMapIntensity:.24});const rockMat=new THREE.MeshStandardMaterial({color:ROCK,roughness:.78,metalness:.025,bumpMap:rockBump,bumpScale:.042,envMapIntensity:.27});const rockDark=new THREE.MeshStandardMaterial({color:0x020302,roughness:.99,metalness:.002});const rubberMat=new THREE.MeshStandardMaterial({color:0x0b0d0c,roughness:.74,metalness:.018,envMapIntensity:.20});const soleMat=new THREE.MeshStandardMaterial({color:0x020302,roughness:.74,metalness:.015});const whiteMat=new THREE.MeshStandardMaterial({color:OFFWHITE,roughness:.34,metalness:.008,envMapIntensity:.28});const limeMat=new THREE.MeshStandardMaterial({color:LIME,roughness:.34,metalness:.015,envMapIntensity:.20});const chromeMat=new THREE.MeshStandardMaterial({color:0xeeeee7,roughness:.20,metalness:.68,envMapIntensity:.74});
let sseed=68217;const rnd=()=>{sseed=(sseed*16807)%2147483647;return(sseed-1)/2147483646};function smoothstep(a,b,x){const t=Math.max(0,Math.min(1,(x-a)/(b-a)));return t*t*(3-2*t)}
const bodyGeo=new THREE.SphereGeometry(2.72,184,138),pos=bodyGeo.attributes.position,craterDefs=[];const faceSafe=n=>n.z>.47&&Math.abs(n.x)<.72&&n.y<.70;
for(let i=0;i<34;i++){let u=rnd()*2-1,a=rnd()*Math.PI*2,ss=Math.sqrt(1-u*u),n=new THREE.Vector3(ss*Math.cos(a),u,ss*Math.sin(a));if(faceSafe(n)){i--;continue}craterDefs.push({n,r:.045+rnd()*.135,d:.042+rnd()*.082,rim:.006+rnd()*.016})}
[[-.30,.86,.40,.28,.20,.020],[.36,.82,.43,.22,.16,.018],[-.72,.47,.48,.19,.13,.015],[.76,.40,.42,.18,.12,.014],[.08,.98,.14,.20,.15,.016],[-.86,.12,.40,.15,.10,.012],[.90,-.04,.34,.15,.10,.012],[.52,-.72,.35,.13,.085,.010]].forEach(a=>craterDefs.push({n:new THREE.Vector3(a[0],a[1],a[2]).normalize(),r:a[3],d:a[4],rim:a[5]}));
const colors=new Float32Array(pos.count*3),baseColor=new THREE.Color(0x151816),pitColor=new THREE.Color(0x010201),rimColor=new THREE.Color(0x353a35);
for(let i=0;i<pos.count;i++){const p=new THREE.Vector3().fromBufferAttribute(pos,i),n=p.clone().normalize();let radius=2.60,maxPit=0,maxRim=0;radius*=1+.005*Math.sin(n.x*7.7+n.y*5.1)+.003*Math.sin(n.z*15.2-n.x*3.8);radius*=1+.022*Math.max(0,-n.y)-.012*Math.max(0,n.y-.42);radius*=1-.018*Math.max(0,n.z)*Math.max(0,1-Math.abs(n.x)*.55);for(const c of craterDefs){const ang=Math.acos(THREE.MathUtils.clamp(n.dot(c.n),-1,1)),inner=c.r*.66,outer=c.r*1.00;if(ang<outer){const pit=1-smoothstep(0,inner,ang),rr=smoothstep(inner*.78,inner,ang)*(1-smoothstep(inner,outer,ang));radius-=c.d*pit;radius+=c.rim*rr;maxPit=Math.max(maxPit,pit);maxRim=Math.max(maxRim,rr)}}p.copy(n.multiplyScalar(radius));p.x*=1.045;p.y*=1.025;p.z*=.962;pos.setXYZ(i,p.x,p.y,p.z);const col=baseColor.clone();if(maxPit>.02)col.lerp(pitColor,Math.min(.96,maxPit*1.05));if(maxRim>.12)col.lerp(rimColor,Math.min(.14,maxRim*.16));const m=.97+.03*(.5+.5*Math.sin(n.x*27+n.y*21+n.z*33));col.multiplyScalar(m);colors[i*3]=col.r;colors[i*3+1]=col.g;colors[i*3+2]=col.b}
pos.needsUpdate=true;bodyGeo.setAttribute('color',new THREE.BufferAttribute(colors,3));bodyGeo.computeVertexNormals();const body=new THREE.Mesh(bodyGeo,bodyMat);body.name='BODY_SCULPT';body.castShadow=true;body.receiveShadow=true;core.add(body);
function taperedTubeGeometry(curve,segments=72,radial=20,r0=.30,r1=.025){const frames=curve.computeFrenetFrames(segments,false),verts=[],idx=[];for(let i=0;i<=segments;i++){const t=i/segments,p=curve.getPointAt(t),rad=THREE.MathUtils.lerp(r0,r1,Math.pow(t,.72)),N=frames.normals[i],B=frames.binormals[i];for(let j=0;j<radial;j++){const a=j/radial*Math.PI*2,off=N.clone().multiplyScalar(Math.cos(a)*rad).add(B.clone().multiplyScalar(Math.sin(a)*rad)),v=p.clone().add(off);verts.push(v.x,v.y,v.z)}}for(let i=0;i<segments;i++)for(let j=0;j<radial;j++){const a=i*radial+j,b=i*radial+(j+1)%radial,c=(i+1)*radial+j,d=(i+1)*radial+(j+1)%radial;idx.push(a,c,b,b,c,d)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setIndex(idx);g.computeVertexNormals();return g}
const crestCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(.72,2.03,-.04),new THREE.Vector3(1.18,2.34,-.18),new THREE.Vector3(1.58,2.32,-.35),new THREE.Vector3(1.90,2.09,-.53),new THREE.Vector3(2.10,1.80,-.65)]);const crest=new THREE.Mesh(taperedTubeGeometry(crestCurve,72,22,.29,.026),rockMat);crest.name='METEOR_CREST';crest.castShadow=true;core.add(crest);