const LIME=0xd8ff1e, ROCK=0x141715, BLACK=0x030403, OFFWHITE=0xf3f2e9;
const stage=document.getElementById('stage'),loading=document.getElementById('loading'),modeLabel=document.getElementById('modeLabel');
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.94;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;stage.appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color(0x020302);scene.fog=new THREE.FogExp2(0x020302,.014);const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(renderer),.022).texture;
const camera=new THREE.PerspectiveCamera(35,innerWidth/innerHeight,.05,180);camera.position.set(7.4,4.4,13.9);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.055;controls.target.set(0,.1,0);controls.minDistance=6;controls.maxDistance=24;
scene.add(new THREE.HemisphereLight(0xffffff,0x050805,1.38));const key=new THREE.DirectionalLight(0xfffdf5,3.20);key.position.set(5.8,9.8,10.8);key.castShadow=true;key.shadow.mapSize.set(2048,2048);scene.add(key);const fill=new THREE.DirectionalLight(0xcbd4ff,.78);fill.position.set(-5,2,8);scene.add(fill);const rim=new THREE.PointLight(LIME,8.5,17,2);rim.position.set(-5,4,-5);scene.add(rim);const backWhite=new THREE.PointLight(0xffffff,6.8,18,2);backWhite.position.set(4,7,-6);scene.add(backWhite);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(160,160),new THREE.MeshStandardMaterial({color:0x030403,roughness:.96,metalness:.02}));floor.rotation.x=-Math.PI/2;floor.position.y=-3.22;floor.receiveShadow=true;scene.add(floor);const grid=new THREE.GridHelper(160,160,0x11160e,0x070a07);grid.position.y=-3.2;grid.material.opacity=.035;grid.material.transparent=true;scene.add(grid);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloomPass=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.44,.58,1.76);composer.addPass(bloomPass);const afterPass=new AfterimagePass(.72);afterPass.enabled=false;composer.addPass(afterPass);
const character=new THREE.Group();character.name='OG_FASTR_CLEAN_MASTER';scene.add(character);character.position.y=.18;const core=new THREE.Group();core.name='PRINTABLE_CORE';character.add(core);const vfx=new THREE.Group();vfx.name='SEPARATE_COMET_VFX';character.add(vfx);
function makeRockBump(){const c=document.createElement('canvas');c.width=c.height=768;const x=c.getContext('2d'),id=x.createImageData(768,768);let r=82736123;const rand=()=>{r=(r*1664525+1013904223)>>>0;return r/4294967296};for(let yy=0;yy<768;yy++)for(let xx=0;xx<768;xx++){const i=(yy*768+xx)*4,coarse=11*Math.sin(xx*.075)+8*Math.cos(yy*.10)+5*Math.sin((xx+yy)*.048),grain=(rand()-.5)*36,v=Math.max(28,Math.min(225,116+coarse+grain));id.data[i]=id.data[i+1]=id.data[i+2]=v;id.data[i+3]=255}x.putImageData(id,0,0);for(let i=0;i<690;i++){const px=rand()*768,py=rand()*768,rr=.5+rand()*2.8;x.fillStyle=`rgba(12,12,12,${.04+rand()*.09})`;x.beginPath();x.arc(px,py,rr,0,Math.PI*2);x.fill()}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(4.4,3.0);t.colorSpace=THREE.NoColorSpace;return t}
const rockBump=makeRockBump();const bodyMat=new THREE.MeshStandardMaterial({color:0xffffff,vertexColors:true,roughness:.79,metalness:.025,bumpMap:rockBump,bumpScale:.105,envMapIntensity:.26});const rockMat=new THREE.MeshStandardMaterial({color:ROCK,roughness:.76,metalness:.03,bumpMap:rockBump,bumpScale:.060,envMapIntensity:.30});const rockDark=new THREE.MeshStandardMaterial({color:0x020302,roughness:.98,metalness:.005});const rubberMat=new THREE.MeshStandardMaterial({color:0x0b0d0c,roughness:.70,metalness:.02,envMapIntensity:.24});const soleMat=new THREE.MeshStandardMaterial({color:0x020302,roughness:.70,metalness:.02});const whiteMat=new THREE.MeshStandardMaterial({color:OFFWHITE,roughness:.30,metalness:.01,envMapIntensity:.34});const limeMat=new THREE.MeshStandardMaterial({color:LIME,roughness:.31,metalness:.02,envMapIntensity:.24});const chromeMat=new THREE.MeshStandardMaterial({color:0xeeeee7,roughness:.18,metalness:.72,envMapIntensity:.82});
let sseed=68217;const rnd=()=>{sseed=(sseed*16807)%2147483647;return(sseed-1)/2147483646};function smoothstep(a,b,x){const t=Math.max(0,Math.min(1,(x-a)/(b-a)));return t*t*(3-2*t)}
const bodyGeo=new THREE.SphereGeometry(2.72,184,138),pos=bodyGeo.attributes.position,craterDefs=[];const faceSafe=n=>n.z>.48&&Math.abs(n.x)<.72&&n.y<.66;
for(let i=0;i<48;i++){let u=rnd()*2-1,a=rnd()*Math.PI*2,ss=Math.sqrt(1-u*u),n=new THREE.Vector3(ss*Math.cos(a),u,ss*Math.sin(a));if(faceSafe(n)){i--;continue}craterDefs.push({n,r:.055+rnd()*.17,d:.085+rnd()*.17,rim:.012+rnd()*.026})}
[[-.30,.86,.40,.28,.29,.040],[.36,.82,.43,.22,.22,.034],[-.72,.47,.48,.19,.18,.030],[.76,.40,.42,.18,.17,.028],[.08,.98,.14,.20,.21,.034],[-.86,.12,.40,.15,.15,.025],[.90,-.04,.34,.15,.15,.027],[.52,-.72,.35,.13,.13,.024]].forEach(a=>craterDefs.push({n:new THREE.Vector3(a[0],a[1],a[2]).normalize(),r:a[3],d:a[4],rim:a[5]}));
const colors=new Float32Array(pos.count*3),baseColor=new THREE.Color(0x151816),pitColor=new THREE.Color(0x010201),rimColor=new THREE.Color(0x4a4f49);
for(let i=0;i<pos.count;i++){const p=new THREE.Vector3().fromBufferAttribute(pos,i),n=p.clone().normalize();let radius=2.60,maxPit=0,maxRim=0;radius*=1+.008*Math.sin(n.x*7.7+n.y*5.1)+.004*Math.sin(n.z*15.2-n.x*3.8);radius*=1+.025*Math.max(0,-n.y)-.017*Math.max(0,n.y-.42);radius*=1-.022*Math.max(0,n.z)*Math.max(0,1-Math.abs(n.x)*.55);for(const c of craterDefs){const ang=Math.acos(THREE.MathUtils.clamp(n.dot(c.n),-1,1)),inner=c.r*.68,outer=c.r*1.08;if(ang<outer){const pit=1-smoothstep(0,inner,ang),rr=smoothstep(inner*.74,inner,ang)*(1-smoothstep(inner,outer,ang));radius-=c.d*pit;radius+=c.rim*rr;maxPit=Math.max(maxPit,pit);maxRim=Math.max(maxRim,rr)}}p.copy(n.multiplyScalar(radius));p.x*=1.055;p.y*=1.035;p.z*=.955;pos.setXYZ(i,p.x,p.y,p.z);const col=baseColor.clone();if(maxPit>.02)col.lerp(pitColor,Math.min(.995,maxPit*1.15));if(maxRim>.10)col.lerp(rimColor,Math.min(.20,maxRim*.20));const m=.95+.05*(.5+.5*Math.sin(n.x*27+n.y*21+n.z*33));col.multiplyScalar(m);colors[i*3]=col.r;colors[i*3+1]=col.g;colors[i*3+2]=col.b}
pos.needsUpdate=true;bodyGeo.setAttribute('color',new THREE.BufferAttribute(colors,3));bodyGeo.computeVertexNormals();const body=new THREE.Mesh(bodyGeo,bodyMat);body.name='BODY_SCULPT';body.castShadow=true;body.receiveShadow=true;core.add(body);
function taperedTubeGeometry(curve,segments=72,radial=20,r0=.30,r1=.025){const frames=curve.computeFrenetFrames(segments,false),verts=[],idx=[];for(let i=0;i<=segments;i++){const t=i/segments,p=curve.getPointAt(t),rad=THREE.MathUtils.lerp(r0,r1,Math.pow(t,.72)),N=frames.normals[i],B=frames.binormals[i];for(let j=0;j<radial;j++){const a=j/radial*Math.PI*2,off=N.clone().multiplyScalar(Math.cos(a)*rad).add(B.clone().multiplyScalar(Math.sin(a)*rad)),v=p.clone().add(off);verts.push(v.x,v.y,v.z)}}for(let i=0;i<segments;i++)for(let j=0;j<radial;j++){const a=i*radial+j,b=i*radial+(j+1)%radial,c=(i+1)*radial+j,d=(i+1)*radial+(j+1)%radial;idx.push(a,c,b,b,c,d)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setIndex(idx);g.computeVertexNormals();return g}
const crestCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(.72,2.02,-.04),new THREE.Vector3(1.18,2.36,-.18),new THREE.Vector3(1.60,2.34,-.36),new THREE.Vector3(1.94,2.10,-.55),new THREE.Vector3(2.15,1.78,-.68)]);const crest=new THREE.Mesh(taperedTubeGeometry(crestCurve,72,22,.32,.030),rockMat);crest.name='METEOR_CREST';crest.castShadow=true;core.add(crest);
